// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw9Q2hlb2vKS3q3Z-QVBlXue43fWj5PwQ',
    appId: '1:672142225413:android:06fded6a8d379762926c6c',
    messagingSenderId: '672142225413',
    projectId: 'flutterfooddite',
    storageBucket: 'flutterfooddite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1pI1JU88voIT2-hr9Fg5JK4X0x9OJ5cY',
    appId: '1:672142225413:ios:9f7482c27abf69da926c6c',
    messagingSenderId: '672142225413',
    projectId: 'flutterfooddite',
    storageBucket: 'flutterfooddite.appspot.com',
    iosBundleId: 'com.example.yailaahi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1pI1JU88voIT2-hr9Fg5JK4X0x9OJ5cY',
    appId: '1:672142225413:ios:9f7482c27abf69da926c6c',
    messagingSenderId: '672142225413',
    projectId: 'flutterfooddite',
    storageBucket: 'flutterfooddite.appspot.com',
    iosBundleId: 'com.example.yailaahi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLvXgRVb4cE3ecrFah9zkdpbYkiEouCBE',
    appId: '1:672142225413:web:4b5bdc2a77873240926c6c',
    messagingSenderId: '672142225413',
    projectId: 'flutterfooddite',
    authDomain: 'flutterfooddite.firebaseapp.com',
    storageBucket: 'flutterfooddite.appspot.com',
    measurementId: 'G-17CKS15BW9',
  );
}
